[package]
name = "greenhouse_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "1.0.109", features = ["full"] }
proc-macro2 = "1"
proc_macro_tools = "0.1.17"

